language: node_js
node_js:
 - "node"

notifications:
  slack: groept:pO9eZDlJOLZfbzZZzYLyUyAC
  email: false

before_script:
 - npm install -g gulp
 - npm install
script: gulp --branch $TRAVIS_BRANCH

branches:
only:
 - master
 - develop